version: 0.5.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
services:
- mongodb
before_build:
  - ps: >-
      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json

      Set-Location -Path ("src")

      dotnet restore

      $a = Get-Content 'C:\projects\ncqs\src\creativeminds.cqs\project.json' -raw | ConvertFrom-Json

      $a.version = $a.version.replace('-*', '.'$env:APPVEYOR_BUILD_NUMBER)

      $a | ConvertTo-Json  | set-content 'C:\projects\ncqs\src\creativeminds.cqs\project.json'

      Get-Content 'C:\projects\ncqs\src\creativeminds.cqs\project.json' | foreach {Write-Output $_}

      $a = Get-Content 'C:\projects\ncqs\src\creativeminds.cqs.ninject\project.json' -raw | ConvertFrom-Json

      $a.update | % {if($_.name -eq 'version'){$_.version=$env:APPVEYOR_BUILD_VERSION}}

      $a | ConvertTo-Json  | set-content 'C:\projects\ncqs\src\creativeminds.cqs.ninject\project.json'

build:
  project: src\creativeminds.cqs.sln
  publish_nuget: true
  verbosity: minimal
before_test:
- ps: #.\Install-MongoDb-On-AppVeyor.ps1
artifacts:
- path: '**\*.nupkg'
