version: 0.9.1.{build}
configuration: Release
init:
- ps: "nuget sources update -Name AppVeyorAccountFeed -Source $env:nuget_source -UserName $env:nuget_user -Password $env:nuget_password"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  nuget_user: nugetrestore@creativeminds.dk
  nuget_password:
    secure: t7dwAMlxY0RY+Ln49o6EKg==
  nuget_source: https://ci.appveyor.com/nuget/creativeminds
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      dotnet restore src\creativeminds.cqs\

      dotnet restore src\creativeminds.cqs.autofac\

build:
    project: src\creativeminds.cqs.sln
    publish_wap: true
    verbosity: normal
after_build:
  - ps: >-
      dotnet pack src\creativeminds.cqs\ -c Release

      dotnet pack src\creativeminds.cqs.autofac\ -c Release

