version: 0.9.1.{build}
configuration: Release
init:
- ps: "nuget sources update -Name AppVeyorAccountFeed -Source $env:nuget_source -UserName $env:nuget_user -Password $env:nuget_password"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  nuget_user: nugetrestore@creativeminds.dk
  nuget_password:
    secure: t7dwAMlxY0RY+Ln49o6EKg==
  nuget_source: https://ci.appveyor.com/nuget/creativeminds
nuget:
  account_feed: true
  project_feed: true
build_script:
  - ps: >-
      dotnet build src\creativeminds.cqs\ -c Release

      dotnet build src\creativeminds.cqs.autofac\ -c Release

after_build:
  - ps: >-
      Push-AppveyorArtifact src\CreativeMinds.CQS\bin\Release\CreativeMinds.CQS.0.9.1.40.nupkg

      Push-AppveyorArtifact src\creativeminds.cqs.autofac\bin\Release\CreativeMinds.CQS.Autofac.0.9.1.40.nupkg

