version: 0.5.0.{build}
configuration: Release
init:
- ps: "nuget sources update -Name AppVeyorAccountFeed -Source $env:nuget_source -UserName $env:nuget_user -Password $env:nuget_password"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: nugetrestore@creativeminds.dk
  nuget_password:
    secure: t7dwAMlxY0RY+Ln49o6EKg==
  nuget_source: https://ci.appveyor.com/nuget/creativeminds
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      nuget restore src\CreativeMinds.CQS.sln

      Set-Location -Path ("src")

      $a = Get-Content 'C:\projects\ncqs\src\creativeminds.cqs\project.json' -raw | ConvertFrom-Json

      $a.version = $a.version.replace('-*', ('.' + $env:APPVEYOR_BUILD_NUMBER))

      $a | ConvertTo-Json  | set-content 'C:\projects\ncqs\src\creativeminds.cqs\project.json'

      $a = Get-Content 'C:\projects\ncqs\src\creativeminds.cqs.ninject\project.json' -raw | ConvertFrom-Json

      $a.version = $a.version.replace('-*', ('.' + $env:APPVEYOR_BUILD_NUMBER))

      $a | ConvertTo-Json  | set-content 'C:\projects\ncqs\src\creativeminds.cqs.ninject\project.json'

build:
  project: src\creativeminds.cqs.sln
  publish_nuget: true
  verbosity: minimal
before_test:
- ps: #.\Install-MongoDb-On-AppVeyor.ps1
artifacts:
- path: '**\*.nupkg'
